### ISSUE TITLE
can not find import class

### ISSUE THREAD

**Issue by bxf12315** [droolsjbpm/jbpm-console-ng#208]
Hi
@Salaboy , I build current mast branch , I find here https://github.com/droolsjbpm/jbpm-console-ng/blob/master/jbpm-console-ng-generic/jbpm-console-ng-data-filters-client/src/main/java/org/jbpm/console/ng/df/client/filter/json/DataSetLookupJSONMarshaller.java#L23

This class not exist in dashbuild. Maybe it was be remove. so I can not maven build jbpm-console-ng.
Please check it. 
Thanks!

**Comment by bxf12315** [comment]
@cristianonicolai Please check it.

**Comment by cristianonicolai** [comment]
Hi @bxf12315, there should be a PR to fix this problem coming out any soon. @nmirasch is working on it.

**Comment by bxf12315** [comment]
@cristianonicolai @nmirasch  Thanks , If you need my help, please feel free to let me know

**Comment by bxf12315** [comment]
It should be close, because of  @nmirasch fixed
